// Top-level build file where you can add configuration options common to all sub-projects/modules.
apply from: "libs/config.gradle"
buildscript {
    repositories {
        google()
        mavenCentral()

        maven { url "https://www.jitpack.io" }
    }

    dependencies {
        classpath "com.android.tools.build:gradle:7.0.4"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.21"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


allprojects {
    repositories {
        google()
        mavenCentral()

        maven { url "https://www.jitpack.io" }
    }
}